name: Windows Defender ASR or Threat Configuration Tamper
id: d0c07718-19d1-4de2-aea9-e0ffff0ed986
version: 1
date: '2025-10-13'
author: Nasreddine Bencherchali, Splunk
status: production
type: TTP
description: |
  The following analytic detects the use of commands to disable Attack Surface Reduction (ASR) rules or change threat default actions in Windows Defender.
  It leverages data from Endpoint Detection and Response (EDR) agents, focusing on command-line executions involving "Add-MpPreference" or "Set-MpPreference".
  This activity is significant because adversaries often use it to bypass Windows Defender, allowing malicious code to execute undetected.
  If confirmed malicious, this behavior could enable attackers to evade antivirus detection, maintain persistence, and execute further malicious activities without interference from Windows Defender.
data_source:
  - Sysmon EventID 1
  - Windows Event Log Security 4688
  - CrowdStrike ProcessRollup2
search: |
  | tstats `security_content_summariesonly` 
    count min(_time) as firstTime 
          max(_time) as lastTime 
          
  from datamodel=Endpoint.Processes where 
  
  Processes.process IN ("*Add-MpPreference *", "*Set-MpPreference *")
  
  Processes.process IN (
        "*-AttackSurfaceReductionRules_Actions*",
        "*-ThreatIDDefaultAction_Actions*"
        )
  
  Processes.process IN (
        "*Allow*", 
        "*NoAction*", 
        "*Disabled*", 
        "*_Actions 6*", 
        "*_Actions 9*", 
        "*_Actions 0*")

  by Processes.action Processes.dest Processes.original_file_name Processes.parent_process
     Processes.parent_process_exec Processes.parent_process_guid Processes.parent_process_id
     Processes.parent_process_name Processes.parent_process_path Processes.process Processes.process_exec
     Processes.process_guid Processes.process_hash Processes.process_id Processes.process_integrity_level
     Processes.process_name Processes.process_path Processes.user Processes.user_id Processes.vendor_product

  | `drop_dm_object_name(Processes)` 
  | `security_content_ctime(firstTime)` 
  | `security_content_ctime(lastTime)`
  | `windows_defender_asr_or_threat_configuration_tamper_filter`
how_to_implement: |
  The detection is based on data that originates from Endpoint Detection
  and Response (EDR) agents. These agents are designed to provide security-related
  telemetry from the endpoints where the agent is installed. To implement this search,
  you must ingest logs that contain the process GUID, process name, and parent process.
  Additionally, you must ingest complete command-line executions. These logs must
  be processed using the appropriate Splunk Technology Add-ons that are specific to
  the EDR product. The logs must also be mapped to the `Processes` node of the `Endpoint`
  data model. Use the Splunk Common Information Model (CIM) to normalize the field
  names and speed up the data modeling process.
known_false_positives: |
  Certain administrative tasks may require the modification of ASR rules or threat actions due to FPs being generated. Investigate all attempts and filter as needed.
references:
  - https://learn.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=windowsserver2025-ps#-attacksurfacereductionrules-actions
  - https://www.virustotal.com/gui/file/7e805617c313ec2fb59d86719c827074cb7dfbf8f0aa18194ac1ffe6c21c8967/behavior
drilldown_searches:
  - name: View the detection results for - "$dest$" and "$user$"
    search: '%original_detection_search% | search  dest = "$dest$" user = "$user$"'
    earliest_offset: $info_min_time$
    latest_offset: $info_max_time$
  - name: View risk events for the last 7 days for - "$dest$" and "$user$"
    search: '| from datamodel Risk.All_Risk | search normalized_risk_object IN ("$dest$",
      "$user$") starthoursago=168  | stats count min(_time) as firstTime max(_time)
      as lastTime values(search_name) as "Search Name" values(risk_message) as "Risk
      Message" values(analyticstories) as "Analytic Stories" values(annotations._all)
      as "Annotations" values(annotations.mitre_attack.mitre_tactic) as "ATT&CK Tactics"
      by normalized_risk_object | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`'
    earliest_offset: $info_min_time$
    latest_offset: $info_max_time$
rba:
  message: ASR or Threat detection tamper activity executed via $process$ on $dest$
  risk_objects:
    - field: user
      type: user
      score: 64
    - field: dest
      type: system
      score: 64
  threat_objects: []
tags:
  analytic_story:
    - Windows Defense Evasion Tactics
  asset_type: Endpoint
  mitre_attack_id:
    - T1562.001
  product:
    - Splunk Enterprise
    - Splunk Enterprise Security
    - Splunk Cloud
  security_domain: endpoint
tests:
  - name: True Positive Test
    attack_data:
    - data: https://media.githubusercontent.com/media/splunk/attack_data/master/datasets/attack_techniques/T1562.001/disable_defender_asr_or_threats/disable_defender_asr_or_threats.log
      source: XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
      sourcetype: XmlWinEventLog
